#!/bin/sh

# PROVIDE: superpay
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# superpay_enable (bool): Set to NO by default. Set this variable to YES if you want to enable superpay service.
# superpay_config (path): Set to /usr/local/etc/superpay.conf by default.
# superpay_user:  The user account superpay daemon runs as. It uses 'root' user by default.
# superpay_group: The group account superpay daemon runs as. It uses 'wheel' group by default.
# superpay_datadir (str): Default to "/var/db/superpay". Base data directory.

. /etc/rc.subr

name=superpay
rcvar=superpay_enable

: ${superpay_enable:=NO}
: ${superpay_config=/usr/local/etc/superpay.conf}
: ${superpay_datadir=/var/db/superpay}
: ${superpay_user="root"}
: ${superpay_group="wheel"}

required_files=${superpay_config}
command=/usr/local/bin/superpayd
superpay_chdir=${superpay_datadir}
pidfile="${superpay_datadir}/superpayd.pid"
stop_cmd=superpay_stop
command_args="-conf=${superpay_config} -datadir=${superpay_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

superpay_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${superpay_datadir}
	[ $? -eq 0 ] && chown -R ${superpay_user}:${superpay_group} ${superpay_datadir}
}

superpay_prestart()
{
	if [ ! -d "${superpay_datadir}/." ]; then
		superpay_create_datadir || return 1
	fi
}

superpay_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

superpay_stop()
{
    superpay_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${superpay_config} -datadir=${superpay_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
